#!/bin/bash
echo "🚀 GitHub Setup Helper"
echo "======================"
echo ""
echo "To complete GitHub setup:"
echo "1. Go to: https://github.com/new"
echo "2. Create repository: 'multi-cloud-least-privilege-mastery'"
echo "3. Make it PUBLIC"
echo "4. Description: 'Master Multi-Cloud Security through Least Privilege - Beginner to Advanced'"
echo "5. DO NOT initialize with README (we already have one)"
echo "6. Follow the 'push existing repository' instructions"
echo ""
echo "Or run these commands after creating the repo:"
echo "git remote add origin https://github.com/YOUR_USERNAME/multi-cloud-least-privilege-mastery.git"
echo "git branch -M main"
echo "git push -u origin main"
